// packages/solid/src/components/button/button.tsx
import { cva } from "class-variance-authority";

import "@radix-ui/colors/plum.css";
import "@radix-ui/colors/plum-dark.css";

import "@radix-ui/colors/teal.css";
import "@radix-ui/colors/teal-dark.css";

import "@radix-ui/colors/grass.css";
import "@radix-ui/colors/grass-dark.css";

import "@radix-ui/colors/red.css";
import "@radix-ui/colors/red-dark.css";

import "@radix-ui/colors/amber.css";
import "@radix-ui/colors/amber-dark.css";

import "@radix-ui/colors/blue.css";
import "@radix-ui/colors/blue-dark.css";

import "@radix-ui/colors/gray.css";
import "@radix-ui/colors/gray-dark.css";

import "@radix-ui/colors/slate.css";
import "@radix-ui/colors/slate-dark.css";
import { ComponentProps, JSXElement } from "solid-js";

type ButtonVariant = "solid" | "secondary" | "outline" | "ghost" | "link";

type ButtonColorScheme =
  | "plum"
  | "teal"
  | "grass"
  | "red"
  | "amber"
  | "blue"
  | "b/w";

type ButtonSize = "sm" | "md" | "lg";

const buttonVariants = cva(
  [
    "inline-flex justify-center items-center",
    "font-semibold",
    "transition-colors",
    "select-none",
    ["disabled:opacity-50", "disabled:pointer-events-none"]
  ],
  {
    compoundVariants: [
      {
        variant: "solid",
        colorScheme: "plum",
        class: [
          "text-[--slate-1]",
          [
            "bg-[--plum-9]",
            "hover:bg-[--plum-10]",
            ["active:bg-[--plum-12]", "dark:active:bg-[--plum-8]"]
          ]
        ]
      },
      {
        variant: "secondary",
        colorScheme: "plum",
        class: [
          "text-[--plum-11]",
          ["bg-[--plum-4]", "hover:bg-[--plum-5]", "active:bg-[--plum-7]"]
        ]
      },
      {
        variant: "outline",
        colorScheme: "plum",
        class: [
          "bg-transparent border",
          "border-[--plum-8]",
          "text-[--plum-11]",
          ["hover:bg-[--plum-4]", "active:bg-[--plum-7]"]
        ]
      },
      {
        variant: "ghost",
        colorScheme: "plum",
        class: [
          "bg-transparent",
          "text-[--plum-11]",
          ["hover:bg-[--plum-4]", "active:bg-[--plum-6]"]
        ]
      },
      {
        variant: "link",
        colorScheme: "plum",
        class: [
          "bg-transparent",
          "text-[--plum-11]",
          ["underline-offset-2", "hover:underline", "active:underline"]
        ]
      },
      {
        variant: "solid",
        colorScheme: "teal",
        class: [
          "text-[--slate-1]",
          "bg-[--teal-9]",
          "hover:bg-[--teal-10]",
          "active:bg-[--teal-11]"
        ]
      },
      {
        variant: "secondary",
        colorScheme: "teal",
        class: [
          "text-[--teal-11]",
          ["bg-[--teal-4]", "hover:bg-[--teal-5]", "active:bg-[--teal-6]"]
        ]
      },
      {
        variant: "outline",
        colorScheme: "teal",
        class: [
          "bg-transparent border",
          "border-[--teal-8]",
          "text-[--teal-11]",
          ["hover:bg-[--teal-4]", "active:bg-[--teal-7]"]
        ]
      },
      {
        variant: "ghost",
        colorScheme: "teal",
        class: [
          "bg-transparent",
          "text-[--teal-11]",
          ["hover:bg-[--teal-4]", "active:bg-[--teal-6]"]
        ]
      },
      {
        variant: "link",
        colorScheme: "teal",
        class: [
          "bg-transparent",
          "text-[--teal-11]",
          ["underline-offset-2", "hover:underline", "active:underline"]
        ]
      },
      {
        variant: "solid",
        colorScheme: "grass",
        class: [
          "text-[--slate-1]",
          ["bg-[--grass-9]", "hover:bg-[--grass-10]", "active:bg-[--grass-11]"]
        ]
      },
      {
        variant: "secondary",
        colorScheme: "grass",
        class: [
          "text-[--grass-11]",
          ["bg-[--grass-4]", "hover:bg-[--grass-5]", "active:bg-[--grass-6]"]
        ]
      },
      {
        variant: "outline",
        colorScheme: "grass",
        class: [
          "bg-transparent border",
          "border-[--grass-8]",
          "text-[--grass-11]",
          ["hover:bg-[--grass-4]", "active:bg-[--grass-7]"]
        ]
      },
      {
        variant: "ghost",
        colorScheme: "grass",
        class: [
          "bg-transparent",
          "text-[--grass-11]",
          ["hover:bg-[--grass-4]", "active:bg-[--grass-6]"]
        ]
      },
      {
        variant: "link",
        colorScheme: "grass",
        class: [
          "bg-transparent",
          "text-[--grass-11]",
          ["underline-offset-2", "hover:underline", "active:underline"]
        ]
      },
      {
        variant: "solid",
        colorScheme: "red",
        class: [
          ["text-[--slate-1]", "dark:text-[--slate-12]"],
          ["bg-[--red-9]", "hover:bg-[--red-10]", "active:bg-[--red-11]"]
        ]
      },
      {
        variant: "secondary",
        colorScheme: "red",
        class: [
          "text-[--red-11]",
          ["bg-[--red-4]", "hover:bg-[--red-5]", "active:bg-[--red-6]"]
        ]
      },
      {
        variant: "outline",
        colorScheme: "red",
        class: [
          "bg-transparent border",
          "border-[--red-8]",
          "text-[--red-11]",
          ["hover:bg-[--red-4]", "active:bg-[--red-7]"]
        ]
      },
      {
        variant: "ghost",
        colorScheme: "red",
        class: [
          "bg-transparent",
          "text-[--red-11]",
          ["hover:bg-[--red-4]", "active:bg-[--red-6]"]
        ]
      },
      {
        variant: "link",
        colorScheme: "red",
        class: [
          "bg-transparent",
          "text-[--red-11]",
          ["underline-offset-2", "hover:underline", "active:underline"]
        ]
      },
      {
        variant: "solid",
        colorScheme: "amber",
        class: [
          ["text-[--slate-12]", "dark:text-[--slate-1]"],
          ["bg-[--amber-9]", "hover:bg-[--amber-10]", "active:bg-[--amber-11]"]
        ]
      },
      {
        variant: "secondary",
        colorScheme: "amber",
        class: [
          "text-[--amber-11]",
          ["bg-[--amber-4]", "hover:bg-[--amber-5]", "active:bg-[--amber-6]"]
        ]
      },
      {
        variant: "outline",
        colorScheme: "amber",
        class: [
          "bg-transparent border",
          "border-[--amber-8]",
          "text-[--amber-11]",
          ["hover:bg-[--amber-4]", "active:bg-[--amber-7]"]
        ]
      },
      {
        variant: "ghost",
        colorScheme: "amber",
        class: [
          "bg-transparent",
          "text-[--amber-11]",
          ["hover:bg-[--amber-4]", "active:bg-[--amber-6]"]
        ]
      },
      {
        variant: "link",
        colorScheme: "amber",
        class: [
          "bg-transparent",
          "text-[--amber-11]",
          ["underline-offset-2", "hover:underline", "active:underline"]
        ]
      },
      {
        variant: "solid",
        colorScheme: "blue",
        class: [
          "text-[--slate-1]",
          ["bg-[--blue-9]", "hover:bg-[--blue-10]", "active:bg-[--blue-11]"]
        ]
      },
      {
        variant: "secondary",
        colorScheme: "blue",
        class: [
          "text-[--blue-11]",
          ["bg-[--blue-4]", "hover:bg-[--blue-5]", "active:bg-[--blue-6]"]
        ]
      },
      {
        variant: "outline",
        colorScheme: "blue",
        class: [
          "bg-transparent border",
          "border-[--blue-8]",
          "text-[--blue-11]",
          ["hover:bg-[--blue-4]", "active:bg-[--blue-7]"]
        ]
      },
      {
        variant: "ghost",
        colorScheme: "blue",
        class: [
          "bg-transparent",
          "text-[--blue-11]",
          ["hover:bg-[--blue-4]", "active:bg-[--blue-6]"]
        ]
      },
      {
        variant: "link",
        colorScheme: "blue",
        class: [
          "bg-transparent",
          "text-[--blue-11]",
          ["underline-offset-2", "hover:underline", "active:underline"]
        ]
      },
      {
        variant: "solid",
        colorScheme: "b/w",
        class: [
          "text-[--slate-1]",
          "bg-[--slate-12]",
          [
            "hover:bg-[--gray-12]",
            "active:bg-[--gray-11]",
            "dark:hover:bg-[--gray-11]",
            "dark:active:bg-[--gray-10]"
          ]
        ]
      },
      {
        variant: "secondary",
        colorScheme: "b/w",
        class: [
          "text-[--gray-12]",
          ["bg-[--gray-5]", "hover:bg-[--gray-6]", "active:bg-[--gray-8]"]
        ]
      },
      {
        variant: "outline",
        colorScheme: "b/w",
        class: [
          "bg-transparent border",
          "border-[--slate-12]",
          "text-[--slate-12]",
          ["hover:bg-[--gray-3]", "active:bg-[--gray-5]"]
        ]
      },
      {
        variant: "ghost",
        colorScheme: "b/w",
        class: [
          "bg-transparent",
          ["text-[--slate-12]", "hover:text-[--slate-1]"],
          ["hover:bg-[--slate-12]", "active:bg-[--gray-11]"]
        ]
      },
      {
        variant: "link",
        colorScheme: "b/w",
        class: [
          "bg-transparent",
          "text-[--slate-12]",
          ["underline-offset-2", "hover:underline", "active:underline"]
        ]
      }
    ],
    variants: {
      variant: {
        solid: "",
        secondary: "",
        outline: "",
        ghost: "",
        link: ""
      },
      colorScheme: {
        plum: "",
        teal: "",
        grass: "",
        red: "",
        amber: "",
        blue: "",
        "b/w": "",
        gray: ""
      },
      size: {
        sm: "h-6 px-2 text-sm rounded",
        md: "h-8 px-3 text-md rounded-md",
        lg: "h-11 px-4 text-lg rounded-lg"
      }
    },
    defaultVariants: {
      colorScheme: "plum",
      size: "md"
    }
  }
);

type ButtonProps = ComponentProps<"button"> & {
  variant?: ButtonVariant;
  colorScheme?: ButtonColorScheme;
  size?: ButtonSize;
  leftIcon?: JSXElement;
  rightIcon?: JSXElement;
};

const Button = ({
  children,
  variant = "solid",
  colorScheme = "plum",
  size = "md",
  leftIcon,
  rightIcon,
  ref,
  ...props
}: ButtonProps) => {
  const isSmall = size === "sm";

  return (
    <button
      class={buttonVariants({ class: props.class, variant, colorScheme, size })}
      {...props}
      ref={ref}
    >
      {leftIcon && <span class={isSmall ? "mr-1" : "mr-2"}>{leftIcon}</span>}
      {children}
      {rightIcon && <span class={isSmall ? "ml-1" : "ml-2"}>{rightIcon}</span>}
    </button>
  );
};

export { Button };
export type { ButtonProps, ButtonVariant, ButtonColorScheme, ButtonSize };

// packages/react/src/button/button.tsx
import React from "react";
import { cva, type VariantProps } from "class-variance-authority";

import "@radix-ui/colors/slate.css";
import "@radix-ui/colors/slate-dark.css";

import "@radix-ui/colors/plum.css";
import "@radix-ui/colors/plum-dark.css";

import "@radix-ui/colors/red.css";
import "@radix-ui/colors/red-dark.css";

import "@radix-ui/colors/green.css";
import "@radix-ui/colors/green-dark.css";

import "@radix-ui/colors/blue.css";
import "@radix-ui/colors/blue-dark.css";

import "@radix-ui/colors/teal.css";
import "@radix-ui/colors/teal-dark.css";

import "@radix-ui/colors/cyan.css";
import "@radix-ui/colors/cyan-dark.css";

// Yellow
import "@radix-ui/colors/amber.css";
import "@radix-ui/colors/amber-dark.css";

import "@radix-ui/colors/orange.css";
import "@radix-ui/colors/orange-dark.css";

import "@radix-ui/colors/gray.css";
import "@radix-ui/colors/gray-dark.css";
import { cn } from "~/utils";

const button = cva(
  [
    "inline-flex justify-center items-center",
    "font-semibold",
    "transition-colors duration-150 active:duration-75",

    // Make text unselectable
    "select-none",

    // Disabled props
    "disabled:opacity-50 disabled:pointer-events-none"
  ],
  {
    variants: {
      colorScheme: {
        purple: null,
        red: null,
        green: null,
        blue: null,
        teal: null,
        cyan: null,
        yellow: null,
        orange: null,
        gray: null
      },

      variant: {
        primary: "text-[var(--slate-1)]",
        secondary: null,
        outline: "border",
        ghost: "bg-transparent"
      },

      size: {
        sm: "h-6 px-2 text-sm rounded",
        md: "h-8 px-3 text-md rounded-md",
        lg: "h-11 px-4 text-lg rounded-lg"
      }
    },

    compoundVariants: [
      // Purple color scheme
      // Primary variant
      {
        colorScheme: "purple",
        variant: "primary",
        className: [
          "bg-[var(--plum-9)]",
          // Hover states
          "hover:bg-[var(--plum-10)]",
          // Active states
          "active:bg-[var(--plum-11)]"
        ]
      },
      // Purple color scheme
      // Secondary variant
      {
        colorScheme: "purple",
        variant: "secondary",
        className: [
          "text-[var(--plum-11)]",
          "bg-[var(--plum-5)]",
          // Hover states
          "hover:bg-[var(--plum-5)]",
          // Active states
          "active:bg-[var(--plum-7)]"
        ]
      },
      // Purple color scheme
      // Outline variant
      {
        colorScheme: "purple",
        variant: "outline",
        className: [
          "text-[var(--plum-11)]",
          "border-[var(--plum-9)]",
          "bg-[var(--plum-3)]",
          // Hover states
          "hover:bg-[var(--plum-4)]",
          // Active states
          "active:bg-[var(--plum-5)]"
        ]
      },
      // Purple color scheme
      // Ghost variant
      {
        colorScheme: "purple",
        variant: "ghost",
        className: [
          "text-[var(--plum-11)]",
          // Hover states
          "hover:bg-[var(--plum-4)]",
          // Active states
          "active:bg-[var(--plum-5)]"
        ]
      },
      // Red color scheme
      // Primary variant
      {
        colorScheme: "red",
        variant: "primary",
        className: [
          "bg-[var(--red-9)]",
          // Hover states
          "hover:bg-[var(--red-10)]",
          // Active states
          "active:bg-[var(--red-11)]"
        ]
      },
      // Red color scheme
      // Secondary variant
      {
        colorScheme: "red",
        variant: "secondary",
        className: [
          "text-[var(--red-11)]",
          "bg-[var(--red-5)]",
          // Hover states
          "hover:bg-[var(--red-5)]",
          // Active states
          "active:bg-[var(--red-7)]"
        ]
      },
      // Red color scheme
      // Outline variant
      {
        colorScheme: "red",
        variant: "outline",
        className: [
          "text-[var(--red-11)]",
          "border-[var(--red-9)]",
          "bg-[var(--red-3)]",
          // Hover states
          "hover:bg-[var(--red-4)]",
          // Active states
          "active:bg-[var(--red-5)]"
        ]
      },
      // Red color scheme
      // Ghost variant
      {
        colorScheme: "red",
        variant: "ghost",
        className: [
          "text-[var(--red-11)]",
          // Hover states
          "hover:bg-[var(--red-4)]",
          // Active states
          "active:bg-[var(--red-5)]"
        ]
      },
      // Green color scheme
      // Primary variant
      {
        colorScheme: "green",
        variant: "primary",
        className: [
          "bg-[var(--green-9)]",
          // Hover states
          "hover:bg-[var(--green-10)]",
          // Active states
          "active:bg-[var(--green-11)]"
        ]
      },
      // Green color scheme
      // Secondary variant
      {
        colorScheme: "green",
        variant: "secondary",
        className: [
          "text-[var(--green-11)]",
          "bg-[var(--green-5)]",
          // Hover states
          "hover:bg-[var(--green-5)]",
          // Active states
          "active:bg-[var(--green-7)]"
        ]
      },
      // Green color scheme
      // Outline variant
      {
        colorScheme: "green",
        variant: "outline",
        className: [
          "text-[var(--green-11)]",
          "border-[var(--green-9)]",
          "bg-[var(--green-3)]",
          // Hover states
          "hover:bg-[var(--green-4)]",
          // Active states
          "active:bg-[var(--green-5)]"
        ]
      },
      // Green color scheme
      // Ghost variant
      {
        colorScheme: "green",
        variant: "ghost",
        className: [
          "text-[var(--green-11)]",
          // Hover states
          "hover:bg-[var(--green-4)]",
          // Active states
          "active:bg-[var(--green-5)]"
        ]
      },
      // Blue color scheme
      // Primary variant
      {
        colorScheme: "blue",
        variant: "primary",
        className: [
          "bg-[var(--blue-9)]",
          // Hover states
          "hover:bg-[var(--blue-10)]",
          // Active states
          "active:bg-[var(--blue-11)]"
        ]
      },
      // Blue color scheme
      // Secondary variant
      {
        colorScheme: "blue",
        variant: "secondary",
        className: [
          "text-[var(--blue-11)]",
          "bg-[var(--blue-5)]",
          // Hover states
          "hover:bg-[var(--blue-5)]",
          // Active states
          "active:bg-[var(--blue-7)]"
        ]
      },
      // Blue color scheme,
      // Outline variant
      {
        colorScheme: "blue",
        variant: "outline",
        className: [
          "text-[var(--blue-11)]",
          "border-[var(--blue-9)]",
          "bg-[var(--blue-3)]",
          // Hover states
          "hover:bg-[var(--blue-4)]",
          // Active states
          "active:bg-[var(--blue-5)]"
        ]
      },
      // Blue color scheme
      // Ghost variant
      {
        colorScheme: "blue",
        variant: "ghost",
        className: [
          "text-[var(--blue-11)]",
          // Hover states
          "hover:bg-[var(--blue-4)]",
          // Active states
          "active:bg-[var(--blue-5)]"
        ]
      },
      // Teal color scheme
      // Primary variant
      {
        colorScheme: "teal",
        variant: "primary",
        className: [
          "bg-[var(--teal-9)]",
          // Hover states
          "hover:bg-[var(--teal-10)]",
          // Active states
          "active:bg-[var(--teal-11)]"
        ]
      },
      // Teal color scheme
      // Secondary variant
      {
        colorScheme: "teal",
        variant: "secondary",
        className: [
          "text-[var(--teal-11)]",
          "bg-[var(--teal-5)]",
          // Hover states
          "hover:bg-[var(--teal-5)]",
          // Active states
          "active:bg-[var(--teal-7)]"
        ]
      },
      // Teal color scheme
      // Outline variant
      {
        colorScheme: "teal",
        variant: "outline",
        className: [
          "text-[var(--teal-11)]",
          "border-[var(--teal-9)]",
          "bg-[var(--teal-3)]",
          // Hover states
          "hover:bg-[var(--teal-4)]",
          // Active states
          "active:bg-[var(--teal-5)]"
        ]
      },
      // Teal color scheme
      // Ghost variant
      {
        colorScheme: "teal",
        variant: "ghost",
        className: [
          "text-[var(--teal-11)]",
          // Hover states
          "hover:bg-[var(--teal-4)]",
          // Active states
          "active:bg-[var(--teal-5)]"
        ]
      },
      // Cyan color scheme
      // Primary variant
      {
        colorScheme: "cyan",
        variant: "primary",
        className: [
          "bg-[var(--cyan-9)]",
          // Hover states
          "hover:bg-[var(--cyan-10)]",
          // Active states
          "active:bg-[var(--cyan-11)]"
        ]
      },
      // Cyan color scheme
      // Secondary variant
      {
        colorScheme: "cyan",
        variant: "secondary",
        className: [
          "text-[var(--cyan-11)]",
          "bg-[var(--cyan-5)]",
          // Hover states
          "hover:bg-[var(--cyan-5)]",
          // Active states
          "active:bg-[var(--cyan-7)]"
        ]
      },
      // Cyan color scheme
      // Outline variant
      {
        colorScheme: "cyan",
        variant: "outline",
        className: [
          "text-[var(--cyan-11)]",
          "border-[var(--cyan-9)]",
          "bg-[var(--cyan-3)]",
          // Hover states
          "hover:bg-[var(--cyan-4)]",
          // Active states
          "active:bg-[var(--cyan-5)]"
        ]
      },
      // Cyan color scheme
      // Ghost variant
      {
        colorScheme: "cyan",
        variant: "ghost",
        className: [
          "text-[var(--cyan-11)]",
          // Hover states
          "hover:bg-[var(--cyan-4)]",
          // Active states
          "active:bg-[var(--cyan-5)]"
        ]
      },
      // Yellow color scheme
      // Primary variant
      {
        colorScheme: "yellow",
        variant: "primary",
        className: [
          // Text is not visible on yellow-9 if not black on both light and dark mode
          "text-[var(--slate-12)] dark:text-[var(--slate-1)]",
          "bg-[var(--amber-9)]",
          // Hover states
          "hover:bg-[var(--amber-10)]",
          // Active states
          "active:bg-[var(--amber-11)]"
        ]
      },
      // Yellow color scheme
      // Secondary variant
      {
        colorScheme: "yellow",
        variant: "secondary",
        className: [
          "text-[var(--amber-11)]",
          "bg-[var(--amber-5)]",
          // Hover states
          "hover:bg-[var(--amber-5)]",
          // Active states
          "active:bg-[var(--amber-7)]"
        ]
      },
      // Yellow color scheme
      // Outline variant
      {
        colorScheme: "yellow",
        variant: "outline",
        className: [
          "text-[var(--amber-11)]",
          "border-[var(--amber-9)]",
          "bg-[var(--amber-3)]",
          // Hover states
          "hover:bg-[var(--amber-4)]",
          // Active states
          "active:bg-[var(--amber-5)]"
        ]
      },
      // Yellow color scheme
      // Ghost variant
      {
        colorScheme: "yellow",
        variant: "ghost",
        className: [
          "text-[var(--amber-11)]",
          // Hover states
          "hover:bg-[var(--amber-4)]",
          // Active states
          "active:bg-[var(--amber-5)]"
        ]
      },
      // Orange color scheme
      // Primary variant
      {
        colorScheme: "orange",
        variant: "primary",
        className: [
          "bg-[var(--orange-9)]",
          // Hover states
          "hover:bg-[var(--orange-10)]",
          // Active states
          "active:bg-[var(--orange-11)]"
        ]
      },
      // Orange color scheme
      // Secondary variant
      {
        colorScheme: "orange",
        variant: "secondary",
        className: [
          "text-[var(--orange-11)]",
          "bg-[var(--orange-5)]",
          // Hover states
          "hover:bg-[var(--orange-5)]",
          // Active states
          "active:bg-[var(--orange-7)]"
        ]
      },
      // Orange color scheme
      // Outline variant
      {
        colorScheme: "orange",
        variant: "outline",
        className: [
          "text-[var(--orange-11)]",
          "border-[var(--orange-9)]",
          "bg-[var(--orange-3)]",
          // Hover states
          "hover:bg-[var(--orange-4)]",
          // Active states
          "active:bg-[var(--orange-5)]"
        ]
      },
      // Orange color scheme
      // Ghost variant
      {
        colorScheme: "orange",
        variant: "ghost",
        className: [
          "text-[var(--orange-11)]",
          // Hover states
          "hover:bg-[var(--orange-4)]",
          // Active states
          "active:bg-[var(--orange-5)]"
        ]
      },
      // Gray color scheme
      // Primary variant
      // Basically black and white
      {
        colorScheme: "gray",
        variant: "primary",
        className: [
          "bg-[var(--gray-12)]",
          // Hover states
          "hover:bg-[var(--gray-12)]",
          // Active states
          "active:bg-[var(--gray-11)]",
          // Diabled props
          "disabled:bg-black",
          "disabled:dark:bg-white"
        ]
      },
      // Gray color scheme
      // Secondary variant
      {
        colorScheme: "gray",
        variant: "secondary",
        className: [
          "text-[var(--gray-12)]",
          "bg-[var(--gray-5)]",
          // Hover states
          "hover:bg-[var(--gray-6)]",
          // Active states
          "active:bg-[var(--gray-7)]"
        ]
      },
      // Gray color scheme
      // Outline variant
      {
        colorScheme: "gray",
        variant: "outline",
        className: [
          "text-[var(--gray-12)]",
          "border-[var(--gray-12)]",
          "bg-[var(--gray-3)]",
          // Hover states
          "hover:bg-[var(--gray-4)]",
          // Active states
          "active:bg-[var(--gray-5)]"
        ]
      },
      // Gray color scheme
      // Ghost variant
      {
        colorScheme: "gray",
        variant: "ghost",
        className: [
          "text-[var(--gray-12)]",
          // Hover states
          "hover:bg-[var(--gray-4)]",
          // Active states
          "active:bg-[var(--gray-5)]"
        ]
      }
    ],

    defaultVariants: {
      colorScheme: "purple",
      variant: "primary",
      size: "md"
    }
  }
);

type ButtonProps = React.ComponentProps<"button"> &
  VariantProps<typeof button> & {
    leftIcon?: React.ReactNode;
    rightIcon?: React.ReactNode;
  };

const Button: React.FC<ButtonProps> = ({
  ref,
  children,
  className,
  colorScheme,
  variant,
  size,
  leftIcon,
  rightIcon,
  ...props
}) => {
  return (
    <button
      className={button({ className, colorScheme, variant, size })}
      {...props}
      ref={ref}
    >
      {leftIcon && (
        <span className={cn(size === "sm" ? "mr-1" : "mr-2")}>{leftIcon}</span>
      )}
      {children}
      {rightIcon && (
        <span className={cn(size === "sm" ? "ml-1" : "mr-2")}>{rightIcon}</span>
      )}
    </button>
  );
};

export { Button };
