// packages/solid/src/components/fundamentals/frame.tsx
import { cn } from "@/lib/utils";

import "@/index.css";

import "@radix-ui/colors/slate.css";
import "@radix-ui/colors/slate-dark.css";
import { ComponentProps, createEffect, createSignal } from "solid-js";
import { IconButton } from "../icon-button";
import { BsMoonFill, BsSun } from "solid-icons/bs";

const Frame = ({
  children,

  full,
  ...props
}: ComponentProps<"div"> & { full?: boolean }) => {
  const [theme, setTheme] = createSignal<"light" | "dark">("light");
  const isDark = theme() === "dark";

  const toggleTheme = () => setTheme(theme() === "light" ? "dark" : "light");

  createEffect(() => {
    const root = document.documentElement;

    if (theme() === "light") {
      root.classList.remove("dark");
    } else {
      root.classList.add("dark");
    }
  });

  return (
    <div class="w-screen h-screen flex justify-center">
      <div
        class={cn(
          full ? "w-screen h-screen" : "w-1/2 h-96",
          "relative flex justify-center items-center bg-[var(--slate-1)] border transition-colors rounded shadow",
          props.class
        )}
        {...props}
      >
        <IconButton
          colorScheme="plum"
          size="sm"
          class={full ? "absolute top-8 right-12" : "absolute top-4 right-4"}
          icon={isDark ? <BsSun /> : <BsMoonFill />}
          onClick={toggleTheme}
        />
        {children}
      </div>
    </div>
  );
};

export { Frame };

// packages/react/src/frame.tsx
// Wrapper for using tailwindcss in storybook

import React, { useEffect, useState } from "react";
import { cn } from "./utils";
import { IconButton } from "./icon-button/icon-button";
import { MoonIcon, SunIcon } from "@radix-ui/react-icons";

import "~/index.css";

const Frame: React.FC<React.ComponentProps<"div">> = ({
  children,
  className,
  ...props
}) => {
  const [theme, setTheme] = useState<"light" | "dark">("light");

  useEffect(() => {
    document.documentElement.classList.remove("dark");
    document.documentElement.classList.remove("light");

    if (theme === "dark") {
      document.documentElement.classList.add("dark");
    } else {
      document.documentElement.classList.add("light");
    }
  }, [theme]);

  return (
    <div
      className={cn(
        className,
        "w-screen h-screen",
        "flex justify-center items-center"
      )}
      {...props}
    >
      <IconButton
        className="absolute top-2 left-2"
        icon={theme === "dark" ? <SunIcon /> : <MoonIcon />}
        onClick={() => setTheme(theme === "dark" ? "light" : "dark")}
      />

      {children}
    </div>
  );
};

export { Frame };
